CREATE TABLE bookings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hostel_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);